"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SUNO_DEFAULT_PADDING_NOISE = exports.SUNO_DEFAULT_ECL = exports.SUNO_DEFAULT_ROTATE = exports.SUNO_DEFAULT_SUB_MARKER = exports.SUNO_DEFAULT_MARKER_SHAPE = exports.SUNO_DEFAULT_PIXEL_STYLE = exports.SUNO_DEFAULT_POSITION = exports.SUNO_DEFAULT_PADDING_LEVEL = exports.SUNO_DEFAULT_RAWURL = exports.SUNO_DEFAULT_ADVANCED = exports.SUNO_DEFAULT_ASPECT_RATIO = exports.SUNO_DEFAULT_MODEL = exports.SUNO_DEFAULT_PRESET = exports.SUNO_DEFAULT_STEPS = exports.SUNO_DEFAULT_QRW = exports.SUNO_SERVICE_ID = void 0;
exports.SUNO_SERVICE_ID = 'f2b646d8-3cfd-46ef-969a-1ea9eebde329';
exports.SUNO_DEFAULT_QRW = 2;
exports.SUNO_DEFAULT_STEPS = 20;
exports.SUNO_DEFAULT_PRESET = '';
exports.SUNO_DEFAULT_MODEL = 'chirp-v4-5';
exports.SUNO_DEFAULT_ASPECT_RATIO = '1:1';
exports.SUNO_DEFAULT_ADVANCED = false;
exports.SUNO_DEFAULT_RAWURL = true;
exports.SUNO_DEFAULT_PADDING_LEVEL = 5;
exports.SUNO_DEFAULT_POSITION = 'center';
exports.SUNO_DEFAULT_PIXEL_STYLE = 'square';
exports.SUNO_DEFAULT_MARKER_SHAPE = 'square';
exports.SUNO_DEFAULT_SUB_MARKER = 'square';
exports.SUNO_DEFAULT_ROTATE = 0;
exports.SUNO_DEFAULT_ECL = 'H';
exports.SUNO_DEFAULT_PADDING_NOISE = 0;
